site_name: Condor User Manual
site_description: Condor User Manual
site_author: Condor Rocks
copyright: Condor Rocks 2016
repo_url: https://github.com/condorrocks/condor/
remote_branch: gh-pages
google_analytics: ['UA-81974709-1', 'docs.condor.rocks']
theme: material
pages:
    - 'Introduction': 'index.md'
    - 'Accounts': 'accounts.md'
    - 'Boards': 'boards.md'
    - 'Feeds': 'feeds.md'
